### ISSUE TITLE
"Cannot read property 'value' of null" when component is destroyed

### ISSUE THREAD

**Issue by mstawick** [DethAriel/ng2-recaptcha#12]
This happens for both untouched captcha, and one that has been resolved.

TypeError: Cannot read property 'value' of null
    at Object.mo [as getResponse] (https://www.gstatic.com/recaptcha/api2/r20170126104253/recaptcha__en_gb.js:298:137)
    at RecaptchaComponent.reset (eval at ./node_modules/ng2-recaptcha/recaptcha/recaptcha.component.js (http://localhost:8000/app.1.js:11315:1), <anonymous>:38:33)
    at RecaptchaComponent.ngOnDestroy (eval at ./node_modules/ng2-recaptcha/recaptcha/recaptcha.component.js (http://localhost:8000/app.1.js:11315:1), <anonymous>:33:14)

**Comment by mstawick** [comment]
And seems to work fine when I remove:

```
       if (this.grecaptcha.getResponse(this.widget)) {
          // Only emit an event in case if something would actually change.
          // That way we do not trigger "touching" of the control if someone does a "reset"
          // on a non-resolved captcha.
          this.resolved.emit(null);
        }
```

from reset() of RecaptchaComponent

**Comment by DethAriel** [comment]
I will take a look at that later today. If this is a blocker, I suggest you to downgrade to v1.5.1

**Comment by DethAriel** [comment]
Please, update to v1.5.4

**Comment by mstawick** [comment]
Thanks!
