### ISSUE TITLE
Cannot find type definition file for 'grecaptcha' when running NG-XI18N

### ISSUE THREAD

**Issue by streamer** [DethAriel/ng2-recaptcha#7]
Hi,
when I try to extract translation strings from my app using ng-xi18n I'm getting this error in recaptcha module... How can I fix this? 

`./node_modules/.bin/ng-xi18n -p ./src/tsconfig.json
Error: Error at /app/node_modules/ng2-recaptcha/recaptcha/recaptcha-loader.service.d.ts:1:1: Cannot find type definition file for 'grecaptcha'.
Error at /app/node_modules/ng2-recaptcha/recaptcha/recaptcha-loader.service.d.ts:6:23: Cannot find namespace 'ReCaptchaV2'.
Error at /app/node_modules/ng2-recaptcha/recaptcha/recaptcha.component.d.ts:1:1: Cannot find type definition file for 'grecaptcha'.
Error at /app/node_modules/ng2-recaptcha/recaptcha/recaptcha.component.d.ts:10:12: Cannot find namespace 'ReCaptchaV2'.
Error at /app/node_modules/ng2-recaptcha/recaptcha/recaptcha.component.d.ts:11:11: Cannot find namespace 'ReCaptchaV2'.
Error at /app/node_modules/ng2-recaptcha/recaptcha/recaptcha.component.d.ts:12:11: Cannot find namespace 'ReCaptchaV2'.
    at UserError.Error (native)
    at new UserError (/app/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/tsc.js:22:34)
    at check (/app/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/tsc.js:73:15)
    at Tsc.typeCheck (/app/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/tsc.js:148:9)
    at /app/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/main.js:56:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Extraction failed
`

**Comment by DethAriel** [comment]
Do you have `@types/grecaptcha` installed as a dependency?

**Comment by DethAriel** [comment]
@streamer were you able to resolve the issue?

**Comment by Sagar-AppLogics** [comment]
https://www.npmjs.com/package/@types/grecaptcha

as suggested by @DethAriel, this works!
